name: cortex_project
channels: 
- defaults
- conda-forge
dependencies:
- python=3.8.5
- numpy
- scipy
- matplotib
- pandas
- soundfile
- jiwer
- cupy
- pytorch=2.0.1
- torchaudio=2.0.2
- tensorflow=2.13
- tensorflow-probability=0.21
- cudatoolkit=11.8
- cudnn=8.6
