
saved_checkpoint: /depot/jgmakin/data/auditory_cortex/pretrained_weights/deepspeech2/librispeech_pretrained_v3.ckpt
use_pca: False

layers:



- layer_name: conv.seq_module.2
  layer_id: 0
  layer_type: conv
  RF: 120 # ms

# - layer_name: conv.seq_module.5
#   layer_id: 1
#   layer_type: conv
#   RF: 320 # ms

# - layer_name: rnns.0.rnn
#   layer_id: 2
#   layer_type: rnn
#   RF: 320 # ms

# - layer_name: rnns.1.rnn
#   layer_id: 3
#   layer_type: rnn
#   RF: 0
# - layer_name: rnns.2.rnn
#   layer_id: 4
#   layer_type: rnn
#   RF: 0
# - layer_name: rnns.3.rnn
#   layer_id: 5
#   layer_type: rnn
#   RF: 0
# - layer_name: rnns.4.rnn
#   layer_id: 6
#   layer_type: rnn
#   RF: 0
