neural_data_dir: /scratch/gilbreth/ahmedb/auditory_cortex
use_pca: False

layers:
- layer_name: wav2vec2.feature_extractor.conv_layers.0.activation   
  bin_width: 1.25
  offset: 0
- layer_name: wav2vec2.feature_extractor.conv_layers.1.activation   
  bin_width: 1.25
  offset: 0
- layer_name: wav2vec2.feature_extractor.conv_layers.2.activation   
  bin_width: 1.25
  offset: 0
- layer_name: wav2vec2.feature_extractor.conv_layers.3.activation   
  bin_width: 1.25
  offset: 0
- layer_name: wav2vec2.feature_extractor.conv_layers.4.activation   
  bin_width: 1.25
  offset: 0
- layer_name: wav2vec2.feature_extractor.conv_layers.5.activation   
  bin_width: 1.25
  offset: 0
- layer_name: wav2vec2.feature_extractor.conv_layers.6.activation   
  bin_width: 1.25
  offset: 0





# - layer_name: wav2vec2.encoder.layer_norm   # this is right after the conv-pos-embedding
#   bin_width: 1.25
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.0.final_layer_norm
#   bin_width: 1.25
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.1.final_layer_norm
#   bin_width: 2.5
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.2.final_layer_norm
#   bin_width: 5
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.3.final_layer_norm
#   bin_width: 10
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.4.final_layer_norm
#   bin_width: 20
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.5.final_layer_norm
#   bin_width: 20
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.6.final_layer_norm
#   bin_width: 20
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.7.final_layer_norm
#   bin_width: 20
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.8.final_layer_norm
#   bin_width: 20
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.9.final_layer_norm
#   bin_width: 20
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.10.final_layer_norm
#   bin_width: 20
#   offset: 0
# - layer_name: wav2vec2.encoder.layers.11.final_layer_norm
#   bin_width: 20
#   offset: 0
