use_pca: False

layers:
- layer_name: model.encoder.conv1
  bin_width: 40
  offset: 0
- layer_name: model.encoder.conv2
  bin_width: 40
  offset: 0
- layer_name: model.encoder.layers.0.final_layer_norm
  bin_width: 40
  offset: 0
- layer_name: model.encoder.layers.1.final_layer_norm
  bin_width: 40
  offset: 0
- layer_name: model.encoder.layers.2.final_layer_norm
  bin_width: 40
  offset: 0
- layer_name: model.encoder.layers.3.final_layer_norm
  bin_width: 40
  offset: 0
