# # windows paths (for my laptop)
# neural_data_dir: C:\Users\ahmedb\projects\auditory_cortex\neural_data_dir #/scratch/gilbreth/ahmedb/auditory_cortex
# results_dir: C:\Users\ahmedb\projects\auditory_cortex\results_dir

# Gilbreth paths (HPC)
neural_data_dir: /scratch/gilbreth/ahmedb/auditory_cortex/
results_dir: /depot/jgmakin/data/auditory_cortex/results/
cache_dir: /scratch/gilbreth/ahmedb/cache

# device that is being used...
hpc_cluster: True
use_cpu: False

neural_datasets:
- 'ucsf'
- 'ucdavis'

dnn_models:
- 'deepspeech2'             # 0
- 'speech2text'             # 1
- 'wav2letter_modified'     # 2
- 'whisper_tiny'            # 3
- 'whisper_base'            # 4
- 'wav2vec2'                # 5
- 'wav2letter_spect'        # 6
- 'w2v2_audioset'           # 7
- 'MERT'                    # 8
- 'CLAP'                    # 9
- 'w2v2_generic'            # 10
- 'spect2vec'               # 11

model_name: wav2letter_modified
identifier: sampling_rate_opt_neural_delay_feature_extractor
# identifier: testing_changes

# identifier: opt_delay_L6_D4 #opt_delay  #_with_audio_zeropad #test7 #RF_delayed_l10-11 #opt_delays_l10-11
delay_features: False
audio_zeropad: False
third: False
delays_grid_search: True

#### Ensure these settings before submitting every job..

bad_sessions:
- '200312'
- '200401'
- '191002'
- '180619'
- '180405'
- '180406'
- '180725'  # this row (included) onwards added 01/24/24 (getting errors for inter-stimulus dead intervals)
- '191212'
- '200226'
- '200610'
- '200325'
- '191002'
- '180619'  # belt sessions here on..
- '200323'
- '200312'
- '190607'  # SPECIAL case: doesn't give any error, but has different distribution of dead intervals..
- '180801'  # PB sessions here on...
- '180417'
- '200617'
- '200401'
delays_param:
  start: 0
  stop: 1
  step: 10
delays:
# - 60
- 0
bin_widths:
- 40
dataset_sizes:
# - 10
- 500
- 501
- 5
k_folds_validation: 3
iterations: 1
LPF_analysis_bw: 10


# optimal_inputs_param:
#   # model_name: wav2letter_modified
#   # model_name: wav2vec2
#   model_name: wav2vec
#   # model_name: speech2text
#   # model_name: whisper
#   starting_sent: 12        # 0 would mean, starting from random noise.
#   # threshold: 0.55 
#   threshold: 0.25
#   force_redo: False
#   sessions: #None
#   - 200206
#   # - 180807
#   # - 180731
#   # - 191113
#   layers:
#   - 3
#   - 4
#   - 5
#   - 6 
#   - 7
#   - 8
#   - 9
#   # - 12
#   # - 13
#   # - 14
#   # - 15


#   # channels: 
#   # - 10
#   # - 32
#   # - 60
#   # - 62

